#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=120gb,walltime=24:00:00
#PBS -N pRF
#PBS -V

#[ $PBS_O_WORKDIR ] && cd $PBS_O_WORKDIR

export SINGULARITYENV_PROCESS_COUNT=4

echo "running pRF"
singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main
if [ ! -s r2.nii.gz ];
then
	echo "output missing"
	exit 1
fi
